// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace oscarproye1.Models
{
    [Table("category")]
    public partial class Category
    {
        [Key]
        [Column("cat_id")]
        public int CatId { get; set; }
        [Required]
        [Column("cat_name")]
        [StringLength(50)]
        [Unicode(false)]
        public string CatName { get; set; }
        [Column("cat_description")]
        [StringLength(255)]
        [Unicode(false)]
        public string CatDescription { get; set; }
        [Column("cat_status")]
        public  Boolean CatStatus { get; set; }
    }
}